[project]
name = "object-detection-gradio"
version = "0.1.0"
description = "Object Detection using Yolo"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gradio>=5.25.2",
    "numpy>=2.1.1",
    "pillow>=11.2.1",
    "torchvision>=0.21.0",
    "ultralytics>=8.3.114",
]
